apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-issuer-operator
  namespace: vault-issuer-namespace
  labels:
    control-plane: vault-issuer-operator
spec:
  selector:
    matchLabels:
      control-plane: vault-issuer-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: vault-issuer-operator
    spec:
      serviceAccountName: percona-vault-issuer
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: perconalab/percona-vault-issuer:0.0.1
        name: vault-issuer
        imagePullPolicy: Always
        env:
          - name: VAULT_SECRET_NAME
            value: "root-token"
          - name: VAULT_TOKEN_FILEPATH
            value: "/some/token/path"
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
