apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-issuer-operator
  namespace: vault-issuer-namespace
  labels:
    control-plane: vault-issuer-operator
spec:
  selector:
    matchLabels:
      control-plane: vault-issuer-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: vault-issuer-operator
    spec:
      serviceAccountName: percona-vault-issuer
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: vault-issuer-image
        name: vault-issuer
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
